version: "3.9"
services:

  pickle-generator:
    image: pickle_generator
    build: 
      context: .
      dockerfile: ./pickle-generator/Dockerfile
    container_name: pickle_generator
    volumes: 
      - ./:/app

