version: "3.9"
services:
  sensorsmock:
    build:
      context: sensors
    ports:
      - "3000:3000"
    environment:
      - SMART_THERMO_BUCKET=d-battalion
      - CARBON_SENSE_URL=http://extract_service:4008/collect_carbon_sense
      - MOISTURE_MATE_URL=http://extract_service:4008/collect_moisture_mate
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=
  extract_service:
    build:
      context: extract
    ports:
      - "4008:4008"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ACCESS_KEY="
      - "MINIO_SECRET_KEY="
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set d-battalion http://minio:9000 Anoosha_Malik anooshamalik1234; /usr/bin/mc mb d-battalion/thermobucketdatabattalion; /usr/bin/mc policy set public d-battalion/thermobucketdatabattalion; exit 0; "
