version: "3.9"
services:
  sensorsmock:
    build: 
      context: sensors
    ports:
      - "3000:3000"
    environment:
      - SMART_THERMO_BUCKET=d-battalion
      - CARBON_SENSE_URL=http://etl_ser:4008/collect_carbon_sense
      - MOISTURE_MATE_URL=http://etl_ser:4008/collect_moisture_mate
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=
  etl_ser:
    build: 
      context: etl
    ports:
      - "4008:4008"
